### ISSUE TITLE
domato patches public?

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/fuzzos#12]
Can the following patches be made public? Perhaps as a gist.
grizzly/corpman/resources/domato/add_fuzzPriv.patch
grizzly/corpman/resources/domato/grammar.patch

**Comment by tysmith** [comment]
This isn't really a fuzzos issue, I'll see about up streaming the changes in grammar.patch. The fuzzpriv changes are replacing the GC calls with GC & CC calls with an alert that most users likely wont want.
