### ISSUE TITLE
`git clone --depth 1` may benefit from `--no-tags --shallow-submodules` as well

### ISSUE THREAD

**Issue by floatingatoll** [MozillaSecurity/fuzzos#14]
I noticed in `fuzzmanager.sh` that we're using `--depth 1`, which implies `--single-branch`, to get a checkout that I suspect we never run git on again. Adding the options `--no-tags` and (if used) `--shallow-submodules` would carry over that intent into git tags (which would be skipped) and submodules (which would get the same depth 1 indication).

I don't know if this will have any significant performance impact, or if the install process cares about git tags, but I figured I'd point it out since we must run this clone quite often.

**Comment by posidron** [comment]
Added `--no--tags` to all git checkouts, that sounds indeed useful.
